In [1]:
import numpy as np

[-1.  1.]


In [12]:
a=np.array([[3,3,5],[3,5,9],[5,9,17]])
b=np.array([1,2,4])
print(np.linalg.solve(a,b))
print('----------------')
a=np.array([[1,2,-1],[2,-2,-2],[-1,3,4]])
b=np.array([-7,-8,8])
print(np.linalg.solve(a,b))
print('----------------')
a=np.array([[2,1,2],[-1,2,-3],[3,2,-1]])
b=np.array([6,0,6])
print(np.linalg.solve(a,b))
print('----------------')
a=np.array([[2,3,5],[3,5,9],[5,9,13]])
b=np.array([4,7,17])
print(np.linalg.solve(a,b))
print('----------------')

[-2.66453526e-16 -5.00000000e-01  5.00000000e-01]
----------------
[-3. -1.  2.]
----------------
[1. 2. 1.]
----------------
[-3.  5. -1.]
----------------


In [16]:
a = np.array([[2,3,1], [0,-1,2],[0,0,3]])
w, v = np.linalg.eig(a)
print(a)
print('Eigenvalue:', w)
print('Eigenvector: ')
print(v)
print('----------------')
a = np.array([[-2,2,-3], [2,1,-6],[-1,-2,0]])
w, v = np.linalg.eig(a)
print(a)
print('Eigenvalue:', w)
print('Eigenvector: ')
print(v)
print('----------------')

[[ 2  3  1]
 [ 0 -1  2]
 [ 0  0  3]]
Eigenvalue: [ 2. -1.  3.]
Eigenvector
[[ 1.         -0.70710678  0.91287093]
 [ 0.          0.70710678  0.18257419]
 [ 0.          0.          0.36514837]]
----------------
[[-2  2 -3]
 [ 2  1 -6]
 [-1 -2  0]]
Eigenvalue: [-3.  5. -3.]
Eigenvector
[[-0.95257934  0.40824829 -0.02296692]
 [ 0.27216553  0.81649658  0.83534731]
 [-0.13608276 -0.40824829  0.54924256]]
----------------
